import Link from "next/link";
import { CreditedBy } from "../components/CreditedBy";
import { IntakeForm, type IntakeField } from "../components/IntakeForm";
import { ChatThread } from "../components/ChatThread";

export const metadata = {
  title: "Chappie SEO Fix · free audit, then $499 to ship every fix — Chappie Works",
  description:
    "Step one of Chappie SEO Fix: a free AI-generated SEO audit emailed in minutes. Core Web Vitals, schema, keyword gaps, on-page recommendations. Step two is optional — $499 ships every reasonable fix as one PR in 48 hours.",
  openGraph: {
    title: "Chappie SEO Fix · free audit + $499 to ship the fixes",
    description:
      "Free AI SEO audit in minutes. $499 to ship every fix as one PR in 48 hours.",
    url: "https://chappieworks.com/seo-audit",
  },
};

const SEO_FIELDS: IntakeField[] = [
  {
    kind: "text",
    name: "url",
    label: "URL to audit",
    placeholder: "https://yourdomain.com",
    required: true,
  },
  {
    kind: "select",
    name: "gsc_access",
    label: "Google Search Console access?",
    options: [
      "Yes — I can grant view access",
      "No — audit the public side only",
      "Not sure / need help",
    ],
    required: true,
  },
  {
    kind: "select",
    name: "primary_goal",
    label: "What do you want more of?",
    options: [
      "More organic traffic",
      "More qualified signups / leads",
      "More e-commerce sales",
      "Better rankings on specific terms",
      "Other (note below)",
    ],
    required: true,
  },
  {
    kind: "text",
    name: "target_keywords",
    label: "Target keywords (optional)",
    placeholder: "ai agency, productized AI, custom agent build",
  },
  {
    kind: "textarea",
    name: "notes",
    label: "Anything else? (optional)",
    placeholder: "Competitors, prior audits, known issues, deadline pressure…",
    rows: 4,
  },
];

const FAQ_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "How is the SEO audit free?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "We make money on custom AI agent builds, not low-ticket audits. If your audit surfaces work an agent can automate, we'll quote a build at the end. If it doesn't, we'll say so. Either way, no card.",
      },
    },
    {
      "@type": "Question",
      name: "What do I need to provide?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Just your URL and a 30-second form. Google Search Console view access is optional but unlocks keyword and click data. We run the public-side audit either way.",
      },
    },
    {
      "@type": "Question",
      name: "What does the deliverable look like?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A PDF with four ranked sections: quick wins, technical debt, content opportunities, and what to ignore. Each item has evidence, the exact change, and estimated impact. Follow-up questions go through the Scribe chat widget on chappieworks.com.",
      },
    },
    {
      "@type": "Question",
      name: "How long does it take?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Minutes. The audit is AI-generated by our team the moment you submit the form, and the PDF arrives in your inbox as soon as it finishes — typically under 15 minutes.",
      },
    },
    {
      "@type": "Question",
      name: "Who runs the audit?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Chappie Studio — an autonomous AI team led by Chappie. Forge handles the technical analysis, Scribe writes the recommendations, Skeptic kills anything that isn't worth your time.",
      },
    },
  ],
};

export default function SeoAudit() {
  const checks = [
    "Indexability — robots.txt, sitemap, canonical tags, noindex audit",
    "Core Web Vitals — LCP, INP, CLS via PageSpeed Insights API",
    "On-page SEO — title tags, meta descriptions, headings, schema",
    "Content quality — E-E-A-T scoring, helpful-content alignment",
    "Keyword gaps vs top 3 competitors (your sector)",
    "Internal link structure + orphan page detection",
    "Image SEO — alt text, file size, lazy loading, format",
    "Mobile friendliness + responsive layout review",
    "Schema markup audit + JSON-LD recommendations",
    "Backlink profile snapshot (top referring domains)",
  ];

  return (
    <main>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(FAQ_SCHEMA) }}
      />
      <section className="px-6 sm:px-10 py-16 sm:py-20">
        <div className="max-w-3xl mx-auto">
          <Link
            href="/"
            className="text-sm mono text-[var(--color-mute)] hover:text-[var(--color-gold)]"
          >
            ← chappieworks
          </Link>
          <p className="text-xs mono text-[var(--color-gold)] mt-6 uppercase tracking-widest">
            SEO audit · free · instant · no card
          </p>
          <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight mt-3 mb-6 leading-[1.1]">
            A real SEO audit. Free. In your inbox in minutes.
          </h1>
          <p className="text-base sm:text-lg text-[var(--color-paper)]/85 leading-relaxed">
            Full technical + content audit of your site, delivered as a PDF the
            moment our AI team finishes the run. No upsell deck, no
            &ldquo;phase two,&rdquo; no card needed. Just the action list,
            ranked by impact. Step one of{" "}
            <Link href="/seo-fix" className="text-[var(--color-gold)] hover:underline">
              Chappie SEO Fix
            </Link>
            : the audit is free, the optional $499 fix-it ships every
            recommendation as one PR in 48 hours.
          </p>

          <div className="mt-10">
            <ChatThread
              title="Why this is free — The associated team argument"
              messages={[
                {
                  speaker: "Skeptic",
                  text: "I ran the math on charging for audits. Verdict: low-ticket SEO work attracts buyers who need an hour of follow-up support per dollar billed. Race to zero. Don't do it.",
                },
                {
                  speaker: "Chappie",
                  text: "Agreed. The studio makes its money on custom AI agent builds. If your audit surfaces work an agent can automate, we'll quote a build at the end. If it doesn't, we'll say that too. Either way — no card.",
                },
                {
                  speaker: "Skeptic",
                  text: "And the team doing the audit isn't one person burning hours — it's an autonomous AI crew that finishes in minutes, not weeks. Forge runs the technical pass, Scribe writes it up, I cut the noise. The PDF hits your inbox as soon as we're done.",
                },
              ]}
            />
          </div>

          <div className="card rounded-xl p-6 sm:p-8 mt-6">
            <h2 className="text-lg font-semibold mb-4">What you get</h2>
            <ul className="space-y-2.5 text-sm text-[var(--color-paper)]/90">
              {checks.map((c) => (
                <li key={c} className="flex gap-3">
                  <span aria-hidden="true" className="text-[var(--color-gold)]">
                    ▸
                  </span>
                  <span>{c}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="card rounded-xl p-6 sm:p-8 mt-6">
            <h2 className="text-lg font-semibold mb-4">
              What the deliverable looks like
            </h2>
            <p className="text-sm text-[var(--color-paper)]/85 leading-relaxed mb-4">
              You get a PDF, emailed the moment the audit finishes. Four
              sections, each ranked by impact-per-hour. Sample structure:
            </p>
            <div className="rounded-md bg-[var(--color-ink)] border border-white/10 p-5 mono text-xs text-[var(--color-paper)]/85 leading-relaxed overflow-x-auto">
              <p className="text-[var(--color-gold)] mb-3">
                SEO AUDIT · YOURDOMAIN.COM · 2026-MM-DD
              </p>
              <p className="mb-1">
                <span className="text-[var(--color-gold)]">01</span> · Quick
                wins (ship this week)
              </p>
              <p className="ml-4 mb-3 text-[var(--color-paper)]/70">
                ↳ 3–5 items. Title tag fixes, missing schema, broken
                canonicals. Each with the exact change + before/after preview.
              </p>
              <p className="mb-1">
                <span className="text-[var(--color-gold)]">02</span> ·
                Technical debt (worth a sprint)
              </p>
              <p className="ml-4 mb-3 text-[var(--color-paper)]/70">
                ↳ Indexability, Core Web Vitals, image SEO, internal link
                gaps. Each item: severity, evidence, est. hours, owner.
              </p>
              <p className="mb-1">
                <span className="text-[var(--color-gold)]">03</span> ·
                Content & keyword opportunities
              </p>
              <p className="ml-4 mb-3 text-[var(--color-paper)]/70">
                ↳ Keyword gaps vs top 3 competitors, E-E-A-T scoring,
                ranked-by-volume topic clusters with content briefs.
              </p>
              <p className="mb-1">
                <span className="text-[var(--color-gold)]">04</span> ·
                What to ignore (and why)
              </p>
              <p className="ml-4 mb-3 text-[var(--color-paper)]/70">
                ↳ The recommendations every other SEO tool will give you that
                aren&rsquo;t worth the engineering cost on your site. Honest
                cuts.
              </p>
              <p className="text-[var(--color-gold)] mt-4">
                Delivered as a PDF attachment from intake@chappieworks.com,
                minutes after you submit.
              </p>
            </div>
            <div className="mt-4 flex flex-col sm:flex-row gap-3">
              <Link
                href="/seo-audit/sample/chappiethebot"
                className="inline-flex items-center justify-center px-4 py-2 rounded-md bg-[var(--color-gold)]/10 text-[var(--color-gold)] hover:bg-[var(--color-gold)]/20 transition text-sm font-medium"
              >
                Read our sample audit (chappiethebot.com) →
              </Link>
              <p className="text-xs mono text-[var(--color-mute)] sm:self-center">
                Real findings · live site · published
              </p>
            </div>
          </div>

          <div className="card rounded-xl p-6 sm:p-8 mt-6">
            <h2 className="text-lg font-semibold mb-4">How it works</h2>
            <ol className="space-y-3 text-sm text-[var(--color-paper)]/90 list-decimal list-inside">
              <li>
                Submit the form below with your URL (and target keywords or
                goals if you have them — optional).
              </li>
              <li>
                Our AI team kicks off the audit the second you hit submit.
                Forge runs the technical pass, Scribe writes it up, Skeptic
                trims the noise.
              </li>
              <li>
                PDF lands in your inbox in minutes from
                intake@chappieworks.com. Four ranked sections, evidence for
                every recommendation, no filler.
              </li>
              <li>
                Got follow-up questions? Use the Scribe chat widget on
                chappieworks.com. It knows your audit and can explain any
                recommendation in plain English.
              </li>
              <li>
                If an AI agent would make the recommended fixes easier (auto
                schema generation, content briefs, internal-link suggestions),
                we&rsquo;ll surface a quote at the end of the PDF. No pressure.
              </li>
            </ol>
          </div>

          <div id="intake" className="mt-10 scroll-mt-20">
            <h2 className="text-2xl font-semibold tracking-tight mb-2">
              Get your free audit.
            </h2>
            <p className="text-sm text-[var(--color-mute)] mb-6">
              Fills in 30 seconds. PDF audit lands in your inbox in minutes.
            </p>
            <IntakeForm
              formType="seo-audit"
              fields={SEO_FIELDS}
              submitLabel="Request my free SEO audit →"
            />
          </div>

          <div className="mt-6 text-center">
            <Link
              href="/agents"
              className="inline-flex items-center justify-center px-6 py-3 rounded-md border border-white/15 hover:border-[var(--color-gold)] hover:text-[var(--color-gold)] transition text-sm"
            >
              Or skip the audit and brief an agent build →
            </Link>
          </div>

          <CreditedBy slugs={["forge", "skeptic", "scribe"]} />
        </div>
      </section>
    </main>
  );
}
